"""baseline schema

Revision ID: 103d2e06c8e1
Revises: 
Create Date: 2026-04-24 07:09:25.818019

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103d2e06c8e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirements',
    sa.Column('title', sa.String(length=256), nullable=False, comment='需求标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='需求详细描述'),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority', native_enum=False, length=16), nullable=False, comment='优先级：high/medium/low'),
    sa.Column('source', sa.Enum('DRE', 'PRODUCT', 'ALGORITHM', 'TEST', name='requirementsource', native_enum=False, length=16), nullable=False, comment='需求来源方：dre/product/algorithm/test'),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='requirementstatus', native_enum=False, length=32), nullable=False, comment='需求状态'),
    sa.Column('feishu_doc_id', sa.String(length=128), nullable=True, comment='飞书文档关联 ID，用于与需求文档联动'),
    sa.Column('dre_owner', sa.String(length=128), nullable=False, comment='Dre 负责人（邮箱或工号）'),
    sa.Column('target_scene', sa.String(length=256), nullable=True, comment='目标场景描述，如：夜间十字路口VRU检测'),
    sa.Column('scene_tags', sa.JSON(), nullable=True, comment="场景标签，如：['夜间','十字路口','VRU']"),
    sa.Column('vehicle_tags', sa.JSON(), nullable=True, comment="车型标签，如：['L4','乘用车']"),
    sa.Column('estimated_data_volume', sa.Integer(), nullable=True, comment='预估所需数据量（帧/条）'),
    sa.Column('due_date', sa.Date(), nullable=True, comment='期望交付日期'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_tasks',
    sa.Column('requirement_id', sa.String(length=36), nullable=False, comment='所属需求 ID'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='任务标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='任务详细描述'),
    sa.Column('task_type', sa.Enum('COLLECTION', 'ANNOTATION', 'PIPELINE', 'QUALITY_CHECK', name='tasktype', native_enum=False, length=32), nullable=False, comment='任务类型：collection/annotation/pipeline/quality_check'),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_SIGNOFF', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', name='taskstatus', native_enum=False, length=32), nullable=False, comment='任务状态'),
    sa.Column('sign_off_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='signoffstatus', native_enum=False, length=16), nullable=False, comment='Sign-off 状态'),
    sa.Column('sign_off_by', sa.String(length=128), nullable=True, comment='审批人'),
    sa.Column('sign_off_at', sa.DateTime(timezone=True), nullable=True, comment='审批时间'),
    sa.Column('sign_off_comment', sa.Text(), nullable=True, comment='审批意见'),
    sa.Column('assigned_to', sa.String(length=128), nullable=True, comment='执行负责人'),
    sa.Column('target_count', sa.Integer(), nullable=False, comment='目标数据量'),
    sa.Column('actual_count', sa.Integer(), nullable=False, comment='实际完成数据量'),
    sa.Column('due_date', sa.Date(), nullable=True, comment='截止日期'),
    sa.Column('x_trace_id', sa.String(length=64), nullable=True, comment='跨系统追踪键，同需求链路共享'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_tasks_x_trace_id'), ['x_trace_id'], unique=False)

    op.create_table('annotation_tasks',
    sa.Column('data_task_id', sa.String(length=36), nullable=False, comment='所属数据任务 ID'),
    sa.Column('clip_uri', sa.String(length=512), nullable=False, comment='切片数据路径'),
    sa.Column('annotation_type', sa.Enum('BBOX_2D', 'BBOX_3D', 'SEMANTIC_SEG', 'LANE_MARKING', 'POINT_CLOUD', 'TRACKING', name='annotationtype', native_enum=False, length=32), nullable=False, comment='标注类型'),
    sa.Column('annotation_vendor', sa.String(length=128), nullable=True, comment='标注供应商'),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'REVIEW', 'ACCEPTED', 'REJECTED', name='annotationstatus', native_enum=False, length=16), nullable=False, comment='标注状态'),
    sa.Column('annotator_id', sa.String(length=128), nullable=True, comment='标注员 ID'),
    sa.Column('reviewer_id', sa.String(length=128), nullable=True, comment='审核员 ID'),
    sa.Column('tpi_score', sa.Float(), nullable=True, comment='人效指标 TPI（Tasks Per Image/Hour）'),
    sa.Column('result_uri', sa.String(length=512), nullable=True, comment='标注结果存储路径'),
    sa.Column('total_objects', sa.Integer(), nullable=False, comment='标注对象总数（框/多边形/点等）'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_task_id'], ['data_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_jobs',
    sa.Column('data_task_id', sa.String(length=36), nullable=False, comment='所属数据任务 ID'),
    sa.Column('vehicle_id', sa.String(length=64), nullable=False, comment='采集车辆编号'),
    sa.Column('route_id', sa.String(length=128), nullable=True, comment='采集路线 ID'),
    sa.Column('status', sa.Enum('SCHEDULED', 'COLLECTING', 'UPLOADED', 'FAILED', name='collectionstatus', native_enum=False, length=16), nullable=False, comment='采集状态'),
    sa.Column('raw_data_uri', sa.String(length=512), nullable=True, comment='原始数据存储路径（对象存储 URI）'),
    sa.Column('total_frames', sa.Integer(), nullable=False, comment='总帧数'),
    sa.Column('collection_config', sa.JSON(), nullable=True, comment='采集配置（传感器参数、频率等）'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True, comment='采集开始时间'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='采集结束时间'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_task_id'], ['data_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('digital_reconstructions',
    sa.Column('data_task_id', sa.String(length=36), nullable=False, comment='所属数据任务 ID'),
    sa.Column('reconstruction_layer', sa.Enum('RAW_PERCEPTION', 'COMPUTING_CONTROL', 'SOFTWARE_ABSTRACTION', name='reconstructionlayer', native_enum=False, length=32), nullable=False, comment='还原层级：raw_perception/computing_control/software_abstraction'),
    sa.Column('sensor_target', sa.Enum('CAMERA', 'LIDAR', 'IMU', 'SRR', 'IRR', 'MCU', 'CAN_SIGNAL', 'VLMU', 'CDCU', 'FPU', 'ROS_TOPIC', 'CABIN_SIGNAL', name='sensortarget', native_enum=False, length=32), nullable=False, comment='传感器/数据源目标'),
    sa.Column('description', sa.Text(), nullable=True, comment='还原目标说明'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='优先级 1-5，5 最高'),
    sa.Column('coverage_status', sa.Enum('NOT_STARTED', 'PARTIAL', 'COMPLETE', name='coveragestatus', native_enum=False, length=16), nullable=False, comment='还原覆盖状态'),
    sa.Column('metadata_json', sa.JSON(), nullable=True, comment='传感器配置等扩展元数据'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_task_id'], ['data_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operations_tasks',
    sa.Column('requirement_id', sa.String(length=36), nullable=False, comment='所属需求 ID'),
    sa.Column('data_task_id', sa.String(length=36), nullable=False, comment='所属数据任务 ID'),
    sa.Column('module', sa.Enum('LABELING', 'TAGGING', 'CHECKING', 'MINING', 'PRIVACY', 'RELEASE', name='operationsmodule', native_enum=False, length=32), nullable=False, comment='运维模块：labeling/tagging/checking/mining/privacy/release'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='运维任务标题'),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='operationstaskstatus', native_enum=False, length=32), nullable=False, comment='执行状态'),
    sa.Column('assigned_to', sa.String(length=128), nullable=True, comment='执行人/小组'),
    sa.Column('x_trace_id', sa.String(length=64), nullable=True, comment='跨系统追踪键，同需求链路共享（HTTP X-Trace-Id 头约定）'),
    sa.Column('payload', sa.JSON(), nullable=True, comment='模块特定配置'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_task_id'], ['data_tasks.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operations_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_tasks_x_trace_id'), ['x_trace_id'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('data_task_id', sa.String(length=36), nullable=False, comment='所属数据任务 ID'),
    sa.Column('x_trace_id', sa.String(length=64), nullable=True, comment='跨系统追踪键（HTTP 头 X-Trace-Id / 日志字段 / 任务参数统一名）'),
    sa.Column('trace_parent_id', sa.String(length=64), nullable=True, comment='父追踪 ID（链路上上一个 span/run 的标识）'),
    sa.Column('requirement_id', sa.String(length=36), nullable=True, comment='冗余需求 ID，便于跨层筛选'),
    sa.Column('operations_task_id', sa.String(length=36), nullable=True, comment='归属的 OperationsTask（可选：采集/流式场景可直接来自 DataTask 或 scheduler）'),
    sa.Column('trigger_source', sa.Enum('DATA_TASK', 'OPERATIONS_TASK', 'SCHEDULER', 'MANUAL', 'EXTERNAL', name='triggersource', native_enum=False, length=32), nullable=False, comment='触发来源：data_task/operations_task/scheduler/manual/external'),
    sa.Column('run_purpose', sa.Enum('INITIAL_BUILD', 'BACKFILL', 'REPAIR', 'REINDEX', 'REPLAY', 'VALIDATION', name='runpurpose', native_enum=False, length=32), nullable=False, comment='运行目的：initial_build/backfill/repair/reindex/replay/validation'),
    sa.Column('pipeline_name', sa.String(length=128), nullable=False, comment='流水线名称'),
    sa.Column('stage', sa.Enum('RAW_INGEST', 'CLIP_EXTRACTION', 'FEATURE_EXTRACTION', 'STRUCTURED_DATASET', name='pipelinestage', native_enum=False, length=32), nullable=False, comment='流水线阶段'),
    sa.Column('input_uri', sa.String(length=512), nullable=False, comment='输入数据路径'),
    sa.Column('output_uri', sa.String(length=512), nullable=True, comment='输出数据路径'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='pipelinestatus', native_enum=False, length=16), nullable=False, comment='执行状态'),
    sa.Column('config', sa.JSON(), nullable=True, comment='流水线配置'),
    sa.Column('metrics', sa.JSON(), nullable=True, comment='执行指标（处理速度、数据量等）'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_task_id'], ['data_tasks.id'], ),
    sa.ForeignKeyConstraint(['operations_task_id'], ['operations_tasks.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_x_trace_id'), ['x_trace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_x_trace_id'))

    op.drop_table('pipeline_runs')
    with op.batch_alter_table('operations_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_tasks_x_trace_id'))

    op.drop_table('operations_tasks')
    op.drop_table('digital_reconstructions')
    op.drop_table('collection_jobs')
    op.drop_table('annotation_tasks')
    with op.batch_alter_table('data_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_tasks_x_trace_id'))

    op.drop_table('data_tasks')
    op.drop_table('requirements')
    # ### end Alembic commands ###
