from pathlib import Path
from typing import Any, BinaryIO, Protocol

from core.domain.models import AuthenticatedUser, ComputeRun, LineageEvent, SampleRecord


class StorageAdapter(Protocol):
    def list_files(self, root: Path) -> list[Path]: ...
    def put_file(self, local_path: Path, target_uri: str) -> str: ...
    def get_file(self, source_uri: str, local_path: Path) -> Path: ...
    def exists(self, uri: str) -> bool: ...
    def size(self, uri: str) -> int: ...
    def list(self, prefix: str) -> list[str]: ...
    def open(self, uri: str, mode: str = 'rb') -> BinaryIO: ...
    def delete(self, uri: str) -> None: ...


class QueryAdapter(Protocol):
    def query(self, sql: str, params: dict[str, Any] | None = None) -> list[dict[str, Any]]: ...
    def create_view(self, name: str, sql: str) -> None: ...
    def register_table(self, name: str, source: str) -> None: ...
    def materialize_table(self, name: str, sql: str) -> None: ...
    def create_sample_table(self, records: list[SampleRecord]) -> None: ...
    def query_distribution(self) -> list[dict[str, Any]]: ...


class ComputeAdapter(Protocol):
    def submit_job(self, job_name: str, payload: dict[str, Any]) -> ComputeRun: ...
    def get_run(self, run_id: str) -> ComputeRun: ...
    def cancel_run(self, run_id: str) -> None: ...


class MetadataAdapter(Protocol):
    def create_workspace(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def list_workspaces(self) -> list[dict[str, Any]]: ...
    def create_dataset(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def list_datasets(self) -> list[dict[str, Any]]: ...
    def get_dataset(self, dataset_id: str) -> dict[str, Any] | None: ...
    def create_dataset_version(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def list_dataset_versions(self, dataset_id: str) -> list[dict[str, Any]]: ...
    def create_job_run(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def list_job_runs(self) -> list[dict[str, Any]]: ...
    def create_task(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def list_tasks(self) -> list[dict[str, Any]]: ...
    def create_export_job(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def list_export_jobs(self) -> list[dict[str, Any]]: ...
    def append_lineage_event(self, payload: LineageEvent) -> dict[str, Any]: ...


class TableAdapter(Protocol):
    def create_table(self, name: str, schema: dict[str, Any], partition_spec: dict[str, Any] | None = None) -> None: ...
    def append(self, name: str, records: list[dict[str, Any]]) -> None: ...
    def overwrite(self, name: str, records: list[dict[str, Any]]) -> None: ...
    def read(self, name: str, filters: dict[str, Any] | None = None) -> list[dict[str, Any]]: ...
    def snapshot(self, name: str) -> str: ...


class SearchAdapter(Protocol):
    def build_index(self, records: list[SampleRecord]) -> None: ...
    def index_samples(self, dataset_version_id: str, records: list[dict[str, Any]]) -> None: ...
    def search_similar(self, vector: list[float], top_k: int = 10) -> list[dict[str, Any]]: ...
    def search_by_filters(self, filters: dict[str, Any], top_k: int = 100) -> list[dict[str, Any]]: ...


class AuthAdapter(Protocol):
    def authenticate(self, username: str, password: str) -> AuthenticatedUser | None: ...
    def issue_token(self, user: AuthenticatedUser) -> str: ...
    def verify_token(self, token: str) -> AuthenticatedUser | None: ...
    def get_user_roles(self, user_id: str, scope: str) -> list[str]: ...
